version: 2
jobs:
  crowdin-upload:
    docker:
      - image: dougley/crowdin
    steps:
      - checkout
      - run: crowdin upload sources
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install packages from apt
          command: apt-get update && apt-get -y install python2.7 python-pip build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev gcc-6 g++-6
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install modules
          command: npm install && npm install --global node-gyp && npm install --save erlpack@latest
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run: git remote add dokku dokku@$DOKKU_SERVER_ADDRESS:switchblade-$CIRCLE_BRANCH
      - run: ssh-keyscan -H $DOKKU_SERVER_ADDRESS >> ~/.ssh/known_hosts
      - run: git push -q -f dokku $CIRCLE_BRANCH:master

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master|dev/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /master|dev/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /master|dev/
  crowdin:
    jobs:
      - crowdin-upload:
          filters:
            branches:
              only: /dev/
