version: 2
jobs:
  crowdin-upload:
    docker:
      - image: alconost/crowdin
    steps:
      - checkout
      - run: crowdin upload resources
workflows:
  version: 2
  crowdin:
    jobs:
      - crowdin-upload:
          filters:
            branches:
              only:
                - master
                - dev
                - circleci