name: Lint
on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: docker://github/super-linter:v3
